### ISSUE TITLE
Is it possible to add additional requests after the execution started?

### ISSUE THREAD

**Issue by tfedor** [chuyskywalker/rolling-curl#19]
E.g. when RollingCurl downloads page I parse it and find out I need to download different page (because of pagination, redirect or something like that).

**Comment by clayliddell** [comment]
@tfedor Yes, this is possible. The second argument of the callback function provided to the `RollingCurl->setCallback()` method references the original RollingCurl object. The referenced object can be used to send a request to another page.

For example:
```
$rollingCurl = new \RollingCurl\RollingCurl();
$url = 'http://reddit.com';
$rollingCurl
    ->get($url)
    ->setCallback(function(\RollingCurl\Request $request, \RollingCurl\RollingCurl $rollingCurl) use ($url) {
            if ($request->getUrl() == $url)
                $rollingCurl->get('google.com');
        })
    ->execute();
```
