### ISSUE TITLE
Is it possible to pass a variable to the anonymous callback function?

### ISSUE THREAD

**Issue by jeffreyroberts** [chuyskywalker/rolling-curl#31]
Lets say I have an array 

    $footprints = array('test', 'test2');

How would I pass it to 

    $rollingCurl->setCallback(function (\RollingCurl\Request $request, \RollingCurl\RollingCurl $rollingCurl) {

**Comment by azkyle** [comment]
You use the 'use' keyword and wrap your parameters in parenthesis right before the opening {.

$rollingCurl->setCallback(function (\RollingCurl\Request $request, \RollingCurl\RollingCurl $rollingCurl) **use ($footprints)** {

**Comment by jeffreyroberts** [comment]
sweeeeet
